<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Martin Nyamu">
<meta name="dcterms.date" content="2024-01-01">

<title>Examining the Determinants and Epidemiological Variability of Active Tuberculosis in Eastern Africa</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="TB Article_files/libs/clipboard/clipboard.min.js"></script>
<script src="TB Article_files/libs/quarto-html/quarto.js"></script>
<script src="TB Article_files/libs/quarto-html/popper.min.js"></script>
<script src="TB Article_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="TB Article_files/libs/quarto-html/anchor.min.js"></script>
<link href="TB Article_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="TB Article_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="TB Article_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="TB Article_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="TB Article_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Examining the Determinants and Epidemiological Variability of Active Tuberculosis in Eastern Africa</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Martin Nyamu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 1, 2024</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>Tuberculosis (TB) is a chronic infectious disease affecting millions worldwide, particularly in developing regions. This study investigates the key determinants of TB incidence across Eastern Africa, focusing on gender, age, and country-specific variations.</p>
  </div>
</div>


</header>


<section id="abstract" class="level1">
<h1>Abstract</h1>
<p><strong>Background</strong>: Tuberculosis (TB) is a chronic infectious disease primarily affecting the lungs but can also spread to other parts of the body, such as the kidneys, spine, brain, and intestines. Despite efforts to control it, TB continues to threaten human lives, especially in developing countries, for over four millennia. It spreads through airborne transmission from person to person.</p>
<p><strong>Objective</strong>: This study aimed to examine the determinants of active TB, exploring the variations in incidence by gender, age group, and country within the Eastern Africa region.</p>
<p><strong>Methods</strong>: A descriptive correlational research design was employed under the positivist paradigm. Aggregated secondary TB data from the World Health Organization (WHO) database was used, with a sample size of 656 cases across Eastern Africa. Data analysis included both descriptive and inferential statistical techniques to investigate the relationships between TB incidences and risk factors.</p>
<p><strong>Results</strong>: Results showed that individuals aged 65 and older are most vulnerable to TB infection. Patients with HIV were found to be particularly at risk due to weakened immune systems, with diabetic patients also more likely to develop TB than smokers. Smokers were twice as likely to develop TB as undernourished individuals, while alcohol consumption was found to have a lesser impact on TB susceptibility than undernourishment. Mozambique, Ethiopia, Kenya, Tanzania, and Uganda were identified as the countries with the highest TB burden in 2018.</p>
<p><strong>Conclusions</strong>: The findings provide insights into the TB epidemic in East Africa and offer data for governments to enhance control, prevention, diagnosis, and treatment strategies.</p>
<p><strong>Keywords</strong>: Tuberculosis, incidence, prevalence, Eastern Africa</p>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Tuberculosis (TB) is a severe infectious disease primarily affecting the lungs, though it can also spread to the kidneys, spine, brain, and intestines (Zaman, 2010). For over 4,000 years, TB has posed a significant health challenge globally, and recent reports indicate that it remains the leading cause of death from infectious diseases, surpassing HIV/AIDS (WHO, 2019). In 2018, more than 10 million people were diagnosed with active TB worldwide, with 1.5 million deaths attributed to the disease.</p>
<p>In Eastern Africa, TB remains prevalent, particularly among men (57% of cases), followed by women (32%) and children (1.1%) (WHO, 2019). Poverty, malnutrition, and limited access to healthcare exacerbate TB in this region, leading to high incidence rates (Kenya Ministry of Health, 2016). Understanding the social, demographic, and biological factors influencing TB transmission is crucial for developing effective prevention and treatment strategies.</p>
<p>This study investigates the determinants of TB incidence across Eastern Africa, focusing on variations by gender, age group, and country.</p>
</section>
<section id="methods" class="level1">
<h1>Methods</h1>
<section id="study-design-and-data-source" class="level2">
<h2 class="anchored" data-anchor-id="study-design-and-data-source">Study Design and Data Source</h2>
<p>This descriptive correlational study used secondary data from the WHO TB database. The data consisted of 656 aggregated TB cases reported across 19 Eastern African countries in 2018. A positivist approach was employed, and the study focused on identifying relationships between TB incidences and potential risk factors.</p>
</section>
<section id="sampling-procedure" class="level2">
<h2 class="anchored" data-anchor-id="sampling-procedure">Sampling Procedure</h2>
<p>The study employed purposive sampling to select the Eastern African countries and variables most relevant to the research questions. Excluded from the analysis were countries outside the Eastern African region and variables not contributing to the research objectives.</p>
</section>
<section id="data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="data-analysis">Data Analysis</h2>
<p>Descriptive statistics were used to summarize the data. Inferential analysis, including two-sample t-tests, one-way ANOVA, and negative binomial regression, was performed using R software to test the study’s hypotheses and examine the relationship between TB and various risk factors such as HIV, diabetes, alcohol, smoking, and malnutrition.</p>
</section>
<section id="hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="hypotheses">Hypotheses</h2>
<ol type="1">
<li><strong>H1</strong>: Males have significantly higher TB incidence than females in Eastern Africa.</li>
<li><strong>H2</strong>: The elderly (65 years and older) experience higher TB incidence across Eastern Africa.</li>
<li><strong>H3</strong>: There is a significant association between TB risk factors (HIV, diabetes, smoking, alcohol, malnutrition) and estimated TB cases in Eastern Africa.</li>
</ol>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="demographic-information" class="level2">
<h2 class="anchored" data-anchor-id="demographic-information">Demographic Information</h2>
<table class="caption-top table">
<caption>Descriptive Statistics by Gender</caption>
<thead>
<tr class="header">
<th>Gender</th>
<th>Mean</th>
<th>SD</th>
<th>Median</th>
<th>Min</th>
<th>Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Female</td>
<td>6412.93</td>
<td>13950.22</td>
<td>1500</td>
<td>0</td>
<td>99000</td>
</tr>
<tr class="even">
<td>Male</td>
<td>10781.98</td>
<td>24689.67</td>
<td>1900</td>
<td>0</td>
<td>165000</td>
</tr>
</tbody>
</table>
<p>Males were more susceptible to TB, with a higher mean incidence (M=10781.98, SD=24689.67) than females (M=6412.93, SD=13950.22).</p>
</section>
<section id="age-groups-and-risk-factors" class="level2">
<h2 class="anchored" data-anchor-id="age-groups-and-risk-factors">Age Groups and Risk Factors</h2>
<table class="caption-top table">
<caption>Descriptive Statistics by Age Group</caption>
<thead>
<tr class="header">
<th>Age Group</th>
<th>Mean</th>
<th>SD</th>
<th>Median</th>
<th>Min</th>
<th>Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>65-74</td>
<td>19249.09</td>
<td>32252.61</td>
<td>3400</td>
<td>0</td>
<td>165000</td>
</tr>
<tr class="even">
<td>15-24</td>
<td>8120.57</td>
<td>20197.04</td>
<td>1000</td>
<td>0</td>
<td>146000</td>
</tr>
</tbody>
</table>
<p>Individuals aged 65-74 were the most affected, with a mean of 19249.09 cases (SD=32252.61), while young adults (15-24) were the second-highest risk group.</p>
</section>
<section id="inferential-analysis" class="level2">
<h2 class="anchored" data-anchor-id="inferential-analysis">Inferential Analysis</h2>
<section id="h1-males-and-tb-incidence" class="level3">
<h3 class="anchored" data-anchor-id="h1-males-and-tb-incidence">H1: Males and TB Incidence</h3>
<p>A two-sample t-test revealed that males had significantly higher TB incidence than females (t = -2.89, p = 0.002).</p>
</section>
<section id="h2-age-and-tb-incidence" class="level3">
<h3 class="anchored" data-anchor-id="h2-age-and-tb-incidence">H2: Age and TB Incidence</h3>
<p>One-way ANOVA showed a significant difference in TB incidence across age groups (F(6, 649) = 11.19, p &lt; 0.001), with the elderly experiencing the highest burden.</p>
</section>
<section id="h3-risk-factors" class="level3">
<h3 class="anchored" data-anchor-id="h3-risk-factors">H3: Risk Factors</h3>
<p>Negative binomial regression indicated that individuals with HIV (RR=2.43, p=0.002), smoking (RR=2.38, p=0.003), and diabetes (RR=1.92, p=0.029) were at significantly higher risk of developing TB.</p>
</section>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>This study confirms that males and the elderly are more susceptible to TB infection in Eastern Africa. It also highlights the importance of addressing HIV, diabetes, and smoking as critical risk factors. Similar to previous research (Ravikumar &amp; Varadaraja, 2017; Berkowitz, 2017), HIV patients were identified as the most vulnerable group, with their weakened immune systems exacerbating TB risk.</p>
<p>The findings provide a foundation for governments in Eastern Africa to enhance TB prevention, diagnosis, and treatment strategies, particularly for at-risk populations such as the elderly, men, and individuals with comorbid conditions like HIV and diabetes.</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>Berkowitz, N. (2017). Effect of diabetes and HIV on radiographic manifestations of pulmonary tuberculosis. <em>University of Cape Town Faculty of Health Sciences Centre for Infectious Disease Epidemiology and Research (CIDER)</em>. <a href="http://hdl.handle.net/11427/25250" class="uri">http://hdl.handle.net/11427/25250</a></p>
<p>Caminero, J. A., Sotgiu, G., Zumla, A., &amp; Migliori, G. B. (2010). Best drug treatment for multidrug-resistant and extensively drug-resistant tuberculosis. <em>The Lancet Infectious Diseases, 10</em>(9), 621–629. https://doi.org/10.1016/S1473-3099(10)70139-0</p>
<p>(And so on. Please add all your references here following the APA format)</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>